name: CareUEveryDay Cron CI

on:
  schedule:
    - cron: '*/1 * * * *'
  push:
     branches:
       - first

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: SendWxTemplateMsg
        run: sudo java -jar ./target/wx-push-0.0.1-SNAPSHOT.jar
